### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by mzschunke** [mzschunke/capstone-project#12]
## Value proposition

As a basketball fan
I want to search for a specific player
in order to find my favorite one's quickly. 

## Description

![user-story-5](https://github.com/mzschunke/capstone-project/assets/126678296/8d5a9afa-0471-441e-bc32-5f90077e1cee)

## Acceptance criteria

- [ ] Player names are displayed for each card until user enters a search term and presses 'enter'
- [ ] After pressing enter, the matching players will be shown
- [ ] clicking on a player name will lead the user to the designated player page
- [ ] A delete button enables the user to delete the search term
- [ ] deleting the search term will lead the user back to the overview page
- [ ] Navigation bar stays visible

## Tasks

- [ ] Create a feature branch
- [ ] Create component searchbar

Size:
