### ISSUE TITLE
Player statistics page 

### ISSUE THREAD

**Issue by mzschunke** [mzschunke/capstone-project#15]
## Value proposition

As a [basketball fan]
I want to [see statistics for any NBA player]
in order to [judge their performances.]

## Description

![user-story-6](https://github.com/mzschunke/capstone-project/assets/126678296/ada9eceb-734f-42e3-8d74-808493b9e81b)

## Acceptance criteria

- [] All players are selectable (dropdown menu)
- [] For now, only seasons 2000-2022 are selectable (dropdown menu)
- [] The table will only be shown if there is data available 
- [] Changing the player name or season will automatically show the new results
- [] Navigation bar stays visible

## Tasks

- [] Create a branch
- [] Component/Search Box
- [] Create a Statistic Page and add a link to the nav bar
- [] Create a table to show results  

Size:
M

**Comment by mzschunke** [comment]
Hi Merle! Thank you for your quick feedback! 

I've fetched the data from a public API, which I've described in previous user stories and thus thought it would be obsolete. 

Your assumption that there are a lot of players is correct. However, I prefer to have a dropdown menu here for the moment (you can still search for the first few letters) -  I might change that at a later point for convenience. :)
