### ISSUE TITLE
Bar Chart 

### ISSUE THREAD

**Issue by mzschunke** [mzschunke/capstone-project#19]
## Value proposition

As a user
I want to see a chart of both selected players stats
in order to compare them in a more comprehensive way.

## Description

![user-story-8](https://github.com/mzschunke/capstone-project/assets/126678296/18dd58d4-3b02-4d0f-b422-d8cf120d8340)

## Acceptance criteria

- [ ] All players are selectable (dropdown menu)
- [ ] The bar chart will only be shown if there is data available for both players
- [ ] Changing a player name or season will automatically update the bar chart 
- [ ] Navigation bar stays visible

## Tasks

 - [ ] Import chart.js
 - [ ] Create Component/Bar Chart 
 - [ ] Create logic to dynamically create a bar chart for selected players.

Size: M
