### ISSUE TITLE
Games Display

### ISSUE THREAD

**Issue by mzschunke** [mzschunke/capstone-project#21]
## Value proposition

As a user
I want to see an overview of all games for each team
in order to to get an overview of their performances.

## Description

![user-story-9](https://github.com/mzschunke/capstone-project/assets/126678296/2caa7119-a2a6-40c3-aece-ee64e318a3c9)

## Acceptance criteria

- [ ] All Seasons are selectable by a drop-down menu
- [ ] If there is no data, an information will get rendered that there is no data available for the selection
- [ ] If there is data available, all games of the selected season get rendered 
- [ ] The rendered game info contains the following: name of home team, name of visiting team and points scored. 

## Tasks

- [ ] Create model/schema for games data
- [ ] Create api/games
- [ ] Create Component/Game Display
- [ ] Implement Game Display on Team detail page 

Size:

M
