### ISSUE TITLE
Player Stats

### ISSUE THREAD

**Issue by mzschunke** [mzschunke/capstone-project#23]
## Value proposition

As a NBA FAN
I want to see an overview of all games of a certain player
to be able to to see how they performed against certain opponents.  

## Description

![user-story-10](https://github.com/mzschunke/capstone-project/assets/126678296/3fdf60b5-6002-4c75-a81a-edcd6ed40ba1)

## Acceptance criteria

- [ ] All seasons are selectable via dropdown
- [ ] If there is no data available, an information will get rendered
- [ ] The rendered stats contain the main stats: points, rebounds, assists, steals & blocks 

## Tasks

- [ ] Create fetch logic with API considering rate limitation
- [ ] Create Component/PlayerStats 
- [ ] Refactor player detail page to implement PlayerStats

Size: M
